import { ReactNode } from "react";

import type { Metadata } from "next";

import { Roboto } from "next/font/google";

import "@/shared/styles/main/main.scss";
import { LayoutClientWrapper } from "@/features/components/containers/LayoutClientWrapper/LayoutClientWrapper";
import { UIControlsProvider } from "@/FontSizeContext/FontSizeContext";
import { Wrapper } from "@/features/components/containers/Wrapper/Wrapper";
import { Footer } from "@/features/components/modules/Footer/Footer";
import { Main } from "@/features/components/ui/Main/Main";

const robotoFont = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Графік відключення електроенергії у Львівській області",
  description: "Generated by create next app",
  icons: "/icons/energy_logo.svg",
  authors: { name: "Andriy Fedoryshyn" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='uk'>
      <body className={robotoFont.className}>
        <LayoutClientWrapper>
          <UIControlsProvider>
            <Wrapper>
              <Main>{children}</Main>
              <Footer />
            </Wrapper>
          </UIControlsProvider>
        </LayoutClientWrapper>
      </body>
    </html>
  );
}
